image: golang:1.9.2
stages:
  - test
  - build-win
#  - build-darwin
#  - build-linux

variables:
  REPO_BASE: github.com/iain17/decentralizer/

before_script:
  - mkdir -p $GOPATH/src/$REPO_BASE
  - cp -r $CI_PROJECT_DIR/* $GOPATH/src/$REPO_BASE
  - cd $GOPATH/src/$REPO_BASE
  - apt-get -y update
  - apt-get -y install upx-ucl
  - cp $GOPATH/src/$REPO_BASE/ci/dep $GOPATH/bin
  - chmod +x $GOPATH/bin/dep
  - cp $GOPATH/src/$REPO_BASE/ci/gx $GOPATH/bin
  - chmod +x $GOPATH/bin/gx
  - make install

test:
  stage: test
  script:
    - go test -v -coverprofile .testCoverage.txt ./...

build-win:
  stage: build-win
  artifacts:
    paths:
    - bin/win/adna.exe
  script:
    - make build-win