image: golang:1.9.2
stages:
  - test
  - build-win
#  - build-darwin
#  - build-linux

variables:
  REPO_BASE: github.com/iain17/decentralizer/

before_script:
  - mkdir -p $GOPATH/src/$REPO_BASE
  - cp -r $CI_PROJECT_PATH/* $GOPATH/src/$REPO_BASE
  - cd $GOPATH/src/$REPO_BASE
#  - apt-get -y update
#  - apt-get -y install build-essential upx-ucl
#  - go get -v -u github.com/whyrusleeping/gx
#  - go get -v -u github.com/golang/dep/cmd/dep
  - make install

test:
  stage: test
  script:
    - go test -v -cover ./...

build-win:
  stage: build-win
  artifacts:
    paths:
    - bin/win/adna.exe
  script:
    - make build-win