image: golang:1.9.2
stages:
  - test
  - build-win
#  - build-darwin
#  - build-linux

variables:
  REPO_BASE: github.com/iain17/decentralizer/

before_script:
  - mkdir -p $GOPATH/src/$REPO_BASE
  - cp -r $CI_PROJECT_DIR/* $GOPATH/src/$REPO_BASE
  - cd $GOPATH/src/$REPO_BASE

test:
  stage: test
  script:
    - cd $GOPATH/src/$REPO_BASE
    - go test -race $(go list ./... | grep -v /vendor/)

build-win:
  stage: build-win
  artifacts:
    paths:
    - bin/win/adna.exe
  script:
    - make build-win